name: two_cars_game
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flame: ^1.16.0
  flame_tiled: ^1.19.0
  flame_svg: ^1.10.0
  flame_noise: ^0.1.1+12
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.13

flutter_launcher_icons:
  image_path_android: "assets/images/2_cars_logo.png"
  image_path_ios: "assets/images/2_cars_logo.png"
  android: true
  ios: true
  adaptive_icon_background: "assets/images/2_cars_logo.png"
  adaptive_icon_foreground: "assets/images/2_cars_logo.png"
  min_sdk_android: 21

flutter_native_splash:
  image: "assets/images/2_cars_logo.png"
  color: "#32306C"

  android_12:
    image: "assets/images/2_cars_logo.png"
    color: "#32306C"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true

  assets:
    - assets/images/
