name: two_cars_game
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flame: ^1.16.0
  flame_tiled: ^1.19.0
  flame_svg: ^1.10.0
  flame_noise: ^0.1.1+12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/2_cars_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
